#!/usr/bin/env python3
"""
Post-commit git hook script.
It checks the version of the current commit and checks if it is newer than
the newest version tag.
If so it sets a tag with the newest version.
Poor mans implementation: first version is 0.0.0
"""
import os
import subprocess

import pkg_resources
from setuptools.config import read_configuration

if __name__ == '__main__':
    git_toplevel = subprocess.check_output(
        'git rev-parse --show-toplevel', shell=True).decode('utf8').splitlines()[0]
    setup_cfg_path = os.path.join(git_toplevel, 'setup.cfg')
    cfg = read_configuration(setup_cfg_path)
    new_version = cfg['metadata']['version']

    last_tags = subprocess.check_output('git tag -l', shell=True).decode('utf8').splitlines()
    last_version = '0.0.0'
    for tag in last_tags:
        v = tag.lstrip('v')
        version = pkg_resources.parse_version(v)
        if (isinstance(v, pkg_resources.extern.packaging.version.Version)
                and not v.is_prerelease and not v.is_postrelease):
            last_version = version.base_version
            break

    if pkg_resources.parse_version(new_version) > pkg_resources.parse_version(last_version):
        subprocess.check_output('git tag v{}'.format(new_version), shell=True)
