sudo: false
language: python
install:
  - pip install pipenv --upgrade
cache: pip
python:
  - '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
jobs:
  include:
    - stage: flake8
      script: make flake8

    - stage: mypy
      script:
        - make mypy

    - stage: pytest
      script:
        - make pytest


