sudo: false
language: python
install:
  - pip install pipenv --upgrade
cache: pip
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - PIPENV_IGNORE_VIRTUALENVS=1 make test
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
