sudo: false
language: python
install:
  - pip install pipenv --upgrade
cache: pip
python:
  - '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - make flake8
  - make mypy
  - make pytest
